In [2]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [3]:
base.shape

(21613, 21)

In [4]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [5]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [6]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

In [8]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [9]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [10]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [11]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [12]:
colunas

[NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [13]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpu9scjcgu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [14]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [15]:
X_treinamento.shape

(15129, 1)

In [16]:
y_treinamento.shape

(15129, 1)

In [17]:
X_teste.shape

(6484, 1)

In [18]:
y_teste.shape

(6484, 1)

In [19]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x': X_treinamento}, y_treinamento,
                                                        batch_size = 32, num_epochs = None, 
                                                        shuffle = True)

In [20]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': X_teste}, y_teste, batch_size = 32, 
                                                  num_epochs = 1000, shuffle = False)

In [21]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Please use `layer.add_weight` method instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpu9scjcgu/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving c

INFO:tensorflow:global_step/sec: 558.912
INFO:tensorflow:loss = 5.9233627, step = 4301 (0.178 sec)
INFO:tensorflow:global_step/sec: 683.433
INFO:tensorflow:loss = 15.236843, step = 4401 (0.146 sec)
INFO:tensorflow:global_step/sec: 673.511
INFO:tensorflow:loss = 12.510292, step = 4501 (0.148 sec)
INFO:tensorflow:global_step/sec: 665.358
INFO:tensorflow:loss = 6.5164833, step = 4601 (0.151 sec)
INFO:tensorflow:global_step/sec: 660.725
INFO:tensorflow:loss = 69.013214, step = 4701 (0.151 sec)
INFO:tensorflow:global_step/sec: 622.453
INFO:tensorflow:loss = 9.5343075, step = 4801 (0.161 sec)
INFO:tensorflow:global_step/sec: 291.197
INFO:tensorflow:loss = 10.346997, step = 4901 (0.346 sec)
INFO:tensorflow:global_step/sec: 539.033
INFO:tensorflow:loss = 23.586597, step = 5001 (0.180 sec)
INFO:tensorflow:global_step/sec: 454.803
INFO:tensorflow:loss = 13.249838, step = 5101 (0.222 sec)
INFO:tensorflow:global_step/sec: 684.113
INFO:tensorflow:loss = 9.64073, step = 5201 (0.145 sec)
INFO:tensorf

In [22]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-08-22T10:33:41Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpu9scjcgu/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Inference Time : 13.42131s
INFO:tensorflow:Finished evaluation at 2020-08-22-10:33:54
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.5143933, global_step = 10000, label/mean = -0.0031915088, loss = 16.460587, prediction/mean = 1.1829

In [ ]:
metricas_teste = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-08-22T10:34:10Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpu9scjcgu/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]


In [ ]:
metricas_treinamento

In [ ]:
metricas_teste

In [ ]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

In [ ]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

In [ ]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = False)

In [ ]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [ ]:
previsoes

In [ ]:
list(previsoes)

In [ ]:
for p in regressor.predict(input_fn = funcao_previsao):
    #print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))